#!/usr/bin/env python3
"""Niri display output switcher.

Switches between internal, external, extend, and duplicate display modes
by writing to output.kdl and reloading the Niri config.

Usage: niri-display.py [internal|external|extend|duplicate]
"""

import sys
import json
import subprocess
import os


def run_cmd(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def notify(title, msg, level="info"):
    icon_map = {"info": "monitor", "error": "error", "warn": "warning", "success": "monitor"}
    icon = icon_map.get(level, "monitor")
    subprocess.run(
        ["qs", "-c", "niri-caelestia-shell", "ipc", "call", "toaster", level, title, msg, icon],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def main():
    if len(sys.argv) < 2:
        print("Usage: niri-display.py [internal|external|extend|duplicate]")
        sys.exit(1)

    mode = sys.argv[1]

    res = run_cmd("niri msg --json outputs")
    if res.returncode != 0:
        notify("Display Switcher", "Error: Niri is not running or IPC failed", "error")
        sys.exit(1)

    try:
        outputs = json.loads(res.stdout)
    except Exception as e:
        notify("Display Switcher", f"Failed to parse Niri outputs: {e}", "error")
        sys.exit(1)

    internal = None
    external = None
    for name in outputs:
        if name.startswith(("eDP", "LVDS", "DSI")):
            internal = name
        else:
            external = name

    if not internal:
        internal = list(outputs.keys())[0] if outputs else "eDP-1"

    if not external:
        if mode in ("external", "extend", "duplicate"):
            notify("Display Switcher", "No external display detected.", "warn")
            mode = "internal"

    run_cmd("pkill wl-mirror")

    # Output kdl is in the same directory as this script (flat structure)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_kdl_path = os.path.join(script_dir, "output.kdl")

    internal_width = 1920
    if internal in outputs:
        modes = outputs[internal].get("modes", [])
        for m in modes:
            if m.get("is_preferred"):
                internal_width = m.get("width", 1920)
                break
        else:
            if modes:
                internal_width = modes[0].get("width", 1920)

    kdl_content = ""
    if mode == "internal":
        kdl_content = f'// Auto-generated by niri-display.py\noutput "{internal}" {{\n    scale 1.0\n}}\n'
        if external:
            kdl_content += f'output "{external}" {{\n    off\n}}\n'
    elif mode == "external":
        kdl_content = f'// Auto-generated by niri-display.py\noutput "{internal}" {{\n    off\n}}\n'
        if external:
            kdl_content += f'output "{external}" {{\n    scale 1.0\n}}\n'
    elif mode == "extend":
        kdl_content = (
            f'// Auto-generated by niri-display.py\n'
            f'output "{internal}" {{\n    position x=0 y=0\n    scale 1.0\n}}\n'
        )
        if external:
            kdl_content += (
                f'output "{external}" {{\n    position x={internal_width} y=0\n    scale 1.0\n}}\n'
            )
    elif mode == "duplicate":
        kdl_content = (
            f'// Auto-generated by niri-display.py\n'
            f'output "{internal}" {{\n    position x=0 y=0\n    scale 1.0\n}}\n'
        )
        if external:
            kdl_content += (
                f'output "{external}" {{\n    position x={internal_width} y=0\n    scale 1.0\n}}\n'
            )
            check_mirror = run_cmd("which wl-mirror")
            if check_mirror.returncode == 0:
                subprocess.Popen(
                    ["wl-mirror", internal],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
            else:
                notify("Mirroring Failed", "wl-mirror is not installed. Mirroring won't work.", "error")

    try:
        os.makedirs(os.path.dirname(output_kdl_path), exist_ok=True)
        with open(output_kdl_path, "w") as f:
            f.write(kdl_content)
    except Exception as e:
        notify("Display Switcher", f"Failed to write config: {e}", "error")
        sys.exit(1)

    run_cmd("niri msg action load-config-file")
    if run_cmd("niri msg action load-config-file").returncode != 0:
        notify("Display Switcher", "Failed to reload Niri config", "error")
        sys.exit(1)

    mode_title = {
        "internal": "Laptop Screen Only",
        "external": "External Screen Only",
        "extend": "Extend Desktop",
        "duplicate": "Duplicate/Mirror",
    }.get(mode, mode)

    notify("Display Switcher", f"Layout changed to {mode_title}", "success")


if __name__ == "__main__":
    main()
