#!/usr/bin/env python3
"""Niri display output switcher.

Switches between internal, external, extend-left, extend-right, and duplicate display modes
by writing to output.kdl and reloading the Niri config.

Usage: niri-display.py [internal|external|extend-left|extend-right|duplicate]
"""

import sys
import json
import subprocess
import os
import time


def run_cmd(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def notify(title, msg, level="info"):
    icon_map = {"info": "monitor", "error": "error", "warn": "warning", "success": "monitor"}
    icon = icon_map.get(level, "monitor")
    subprocess.run(
        ["qs", "-c", "niri-caelestia-shell", "ipc", "call", "toaster", level, title, msg, icon],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def find_quickshell_pids():
    """Find quickshell process IDs by exact process name match."""
    pids = []
    for name in ["quickshell", "qs"]:
        result = subprocess.run(
            ["pgrep", "-x", name],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            pids.extend([int(pid) for pid in result.stdout.strip().splitlines()])
    return list(set(pids))


def kill_quickshell():
    """Kill quickshell by PID with SIGKILL to prevent use-after-free crash."""
    pids = find_quickshell_pids()
    if not pids:
        return

    for pid in pids:
        subprocess.run(["kill", "-9", str(pid)], capture_output=True)

    for _ in range(20):
        remaining = find_quickshell_pids()
        if not remaining:
            return
        time.sleep(0.1)

    for pid in pids:
        subprocess.run(["kill", "-9", str(pid)], capture_output=True)


def restart_quickshell():
    """Restart quickshell after display change."""
    subprocess.Popen(
        ["qs", "-c", "niri-caelestia-shell"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )


def main():
    if len(sys.argv) < 2:
        print("Usage: niri-display.py [internal|external|extend-left|extend-right|duplicate]")
        sys.exit(1)

    mode = sys.argv[1]
    turning_off_display = mode in ("internal", "external")

    res = run_cmd("niri msg --json outputs")
    if res.returncode != 0:
        if turning_off_display:
            restart_quickshell()
        notify("Display Switcher", "Error: Niri is not running or IPC failed", "error")
        sys.exit(1)

    try:
        outputs = json.loads(res.stdout)
    except Exception as e:
        if turning_off_display:
            restart_quickshell()
        notify("Display Switcher", f"Failed to parse Niri outputs: {e}", "error")
        sys.exit(1)

    internal = None
    external = None
    for name in outputs:
        if name.startswith(("eDP", "LVDS", "DSI")):
            internal = name
        else:
            external = name

    if not internal:
        internal = list(outputs.keys())[0] if outputs else "eDP-1"

    if not external:
        if mode in ("external", "extend", "extend-left", "extend-right", "duplicate"):
            notify("Display Switcher", "No external display detected.", "warn")
            mode = "internal"

    run_cmd("pkill wl-mirror")

    # Output kdl is in the same directory as this script (flat structure)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    output_kdl_path = os.path.join(script_dir, "output.kdl")

    internal_width = 1920
    if internal in outputs:
        modes = outputs[internal].get("modes", [])
        for m in modes:
            if m.get("is_preferred"):
                internal_width = m.get("width", 1920)
                break
        else:
            if modes:
                internal_width = modes[0].get("width", 1920)

    external_width = 1920
    if external and external in outputs:
        modes = outputs[external].get("modes", [])
        for m in modes:
            if m.get("is_preferred"):
                external_width = m.get("width", 1920)
                break
        else:
            if modes:
                external_width = modes[0].get("width", 1920)

    kdl_content = ""
    if mode == "internal":
        kdl_content = f'// Auto-generated by niri-display.py\noutput "{internal}" {{\n    scale 1.0\n}}\n'
        if external:
            kdl_content += f'output "{external}" {{\n    off\n}}\n'
    elif mode == "external":
        kdl_content = f'// Auto-generated by niri-display.py\noutput "{internal}" {{\n    off\n}}\n'
        if external:
            kdl_content += f'output "{external}" {{\n    scale 1.0\n}}\n'
    elif mode == "extend-left":
        # External on the left, internal on the right
        kdl_content = f'// Auto-generated by niri-display.py\noutput "{internal}" {{\n    position x={external_width} y=0\n    scale 1.0\n}}\n'
        if external:
            kdl_content += f'output "{external}" {{\n    position x=0 y=0\n    scale 1.0\n}}\n'
    elif mode == "extend-right":
        # Internal on the left, external on the right
        kdl_content = f'// Auto-generated by niri-display.py\noutput "{internal}" {{\n    position x=0 y=0\n    scale 1.0\n}}\n'
        if external:
            kdl_content += f'output "{external}" {{\n    position x={internal_width} y=0\n    scale 1.0\n}}\n'
    elif mode == "duplicate":
        kdl_content = (
            f'// Auto-generated by niri-display.py\n'
            f'output "{internal}" {{\n    position x=0 y=0\n    scale 1.0\n}}\n'
        )
        if external:
            kdl_content += (
                f'output "{external}" {{\n    position x={internal_width} y=0\n    scale 1.0\n}}\n'
            )
            check_mirror = run_cmd("which wl-mirror")
            if check_mirror.returncode == 0:
                subprocess.Popen(
                    ["wl-mirror", internal],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
            else:
                notify("Mirroring Failed", "wl-mirror is not installed. Mirroring won't work.", "error")

    # Write output.kdl
    try:
        os.makedirs(os.path.dirname(output_kdl_path), exist_ok=True)
        with open(output_kdl_path, "w") as f:
            f.write(kdl_content)
    except Exception as e:
        if turning_off_display:
            restart_quickshell()
        notify("Display Switcher", f"Failed to write config: {e}", "error")
        sys.exit(1)

    # -- Quickshell crash guard --
    if turning_off_display:
        kill_quickshell()

    # Reload niri config
    if mode == "internal":
        run_cmd(f"niri msg output {internal} on")
    res_reload = run_cmd("niri msg action load-config-file")
    if res_reload.returncode != 0:
        if turning_off_display:
            restart_quickshell()
        notify("Display Switcher", "Failed to reload Niri config", "error")
        sys.exit(1)

    if turning_off_display:
        restart_quickshell()

    mode_title = {
        "internal": "Laptop Screen Only",
        "external": "External Screen Only",
        "extend": "Extend Desktop",
        "extend-left": "Extend Left",
        "extend-right": "Extend Right",
        "duplicate": "Duplicate/Mirror",
    }.get(mode, mode)

    if not turning_off_display:
        notify("Display Switcher", f"Layout changed to {mode_title}", "success")


if __name__ == "__main__":
    main()
