# chadmux Theme (matugen-aware)
set -g status-interval 1
set -g status-left-length 100

set -g status-left "#{?pane_in_mode,#[bold fg=#{@thm_on_surface}]#[bg=#{@thm_error}]  COPY #[fg=#{@thm_error} bg=#{@thm_secondary_fixed}],#{?window_zoomed_flag,#[bold fg=#{@thm_on_surface}]#[bg=#{@thm_outline}]  ZOOM #[fg=#{@thm_outline} bg=#{@thm_secondary_fixed}],#{?client_prefix,#[bold fg=#{@thm_on_surface}]#[bg=#{@thm_secondary}]  CMND #[fg=#{@thm_secondary} bg=#{@thm_secondary_fixed}],#[bold fg=#{@thm_on_surface}]#[bg=#{@thm_surface_bright}]  TMUX #[fg=#{@thm_surface_bright} bg=#{@thm_secondary_fixed}]}}}"

set -ag status-left "#[fg=#{@thm_secondary_fixed} bg=#{@thm_error}]"

# Agregar el nombre de la sesión
set -ag status-left "#[fg=#{@thm_tertiary_container} bg=#{@thm_error}]  #(basename $SHELL) #[fg=#{@thm_error} bg=#{@thm_error}]"
set -ag status-left "#[fg=#{@thm_error} bg=#{@thm_tertiary_fixed}]"

set -ag status-left "#[fg=#{@thm_surface} bg=#{@thm_tertiary_fixed}]  #S #{}"
set -ag status-left "#[fg=#{@thm_tertiary_fixed} bg=#{@thm_surface}]"

set -ag status-left "#[bg=#{@thm_surface}] "





set -g status-right "#[fg=#{@thm_surface_bright}] #{pane_current_command} "

# TIME
set -ag status-right "#[fg=#{@thm_tertiary_fixed}]#[fg=#{@thm_surface} bg=#{@thm_tertiary_fixed}]󰥔 #[fg=#{@thm_tertiary_fixed} bg=#{@thm_surface}] %H:%M #{}"

set -g status-bg #{@thm_surface}
set -g status-fg #{@thm_secondary_fixed}

set -g pane-active-border-style "fg=#{@thm_tertiary}"
set -g pane-border-style "fg=#{@thm_surface}"

# Window inactives
set -g window-status-format "#[default]#{window_index} #{b:pane_current_path}"

# Window active
set -g window-status-current-format "#[fg=#{@thm_surface} bg=#{@thm_primary}]#[bold fg=#{@thm_surface} bg=#{@thm_primary}] #{window_index} #{b:pane_current_path} #[fg=#{@thm_primary} bg=#{@thm_surface}]"

# Pane border
setw -g pane-border-status bottom
set -g pane-border-format "#[align=centre]#{?pane_active,#[bold],#[fg=black,bg=default]} #{pane_index} • #{?pane_active,#[bold],#[fg=black,bg=default]}#{pane_current_command} "
setw -g pane-border-lines single
